[package]
name = "ris_ptr"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ris_error = { path = "../ris_error" }
ris_log = { path = "../ris_log" }
